### PR TITLE
Serialization Rework

### LINKED ISSUE #192: [Technical] Speicherformat umbauen
Das aktuelle Speicherformat (einzelne XML-Datei für jeweils World, Space und Element) ist nicht einsetzbar. Wir müssen umbauen auf einen Ansatz mit mehreren kleinen Beschreibungsdateien.

### PR DESCRIPTION
**Pull request by niklasstich**
- Changed Serialization from XmlSerializer to DataContractSerializer
- Added and adjusted tests for this new serializer
- Changed LearningContent Content property from byte array to a filepath, meaning we don't load all content in memory constantly
- Instead, content is now copied into an application data directory where it is referenced by the LearningContent objects
- Introduced new functionality in ContentFileHandler to handle copying content files into said directory and finding and managing duplicate files (duplicate by content, not name)
- Added and adjusted tests for this new functionality
- Added temporary workaround for sharpziplib bug where we cannot generate proper Tar archives on unix systems (this is fixed by upgrading to 1.4.0 via #204, but we cannot currently upgrade to that version because it breaks our backup generation)
Closes #192

### CODE REVIEW

**Comment by DimitriB01** [comment]
Fehler beim Export 

stdout: fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'MBn1p_t9SqMBcP6s-YJnJ8OwEZkQv0rURMcZ8ulhslE'.
      System.IO.IOException: The file 'C:\Users\biglerdd\AppData\Local\Temp\qvcqw3qi.3m1\roles.xml' already exists.
         at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
         at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
         at System.IO.File.Copy(String sourceFileName, String destFileName)
         at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName)
         at Generator.WorldExport.BackupFileGenerator.DirectoryCopy(String source, String targetPrefix) in C:\Users\biglerdd\RiderProjects\AutorenTool_1\AutorenTool_2\Generator\WorldExport\BackupFileGenerator.cs:line 110
         at Generator.WorldExport.BackupFileGenerator.WriteBackupFile(String filepath) in C:\Users\biglerdd\RiderProjects\AutorenTool_1\AutorenTool_2\Generator\WorldExport\BackupFileGenerator.cs:line 52
         at Generator.API.WorldGenerator.ConstructBackup(LearningWorld learningWorld, String filepath) in C:\Users\biglerdd\RiderProjects\AutorenTool_1\AutorenTool_2\Generator\API\WorldGenerator.cs:line 36
         at BusinessLogic.API.BusinessLogic.ConstructBackup(LearningWorld learningWorld, String filepath) in C:\Users\biglerdd\RiderProjects\AutorenTool_1\AutorenTool_2\BusinessLogic\API\BusinessLogic.cs:line 33
         at Presentation.PresentationLogic.API.PresentationLogic.ConstructBackupAsync(LearningWorldViewModel learningWorldViewModel) in C:\Users\biglerdd\RiderProjects\AutorenTool_1\AutorenTool_2\Presentation\PresentationLogic\API\PresentationLogic.cs:line 61
         at Presentation.View.AuthoringToolWorkspaceView.ExportLearningWorld() in C:\Users\biglerdd\RiderProjects\AutorenTool_1\AutorenTool_2\Presentation\View\AuthoringToolWorkspaceView.razor:line 215
         at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---

**Comment by DimitriB01** [comment]
Die Export Funktion wurde mit allen vorhandenen Lernelementen getestet.

**Review by DimitriB01 — COMMENTED** [review]
Die Export Funktion wurde mit allen vorhandenen Lernelementen getestet.

**Review by andreasweishaupt — APPROVED** [review]
Verschiedene Funktionen, die im Autorentool für den Nutzer möglich sind, wurden getestet.

**Pull request merged**
